### VARIABLES
@apiUrl = http://localhost:3000
@idCategory = 650241d08b749dabdeacceb9


### HEALTH CHECK
GET {{apiUrl}}/health-check

### GET LIST OF CATEGORY
GET {{apiUrl}}/category

### GET ONE CATEGORY
GET {{apiUrl}}/category/{{idCategory}}

### POST ONE CATEGORY
POST {{apiUrl}}/category
content-type: application/json

{
    "name": "Drinks"
}

### UPDATE ONE CATEGORY
PUT {{apiUrl}}/category/{{idCategory}}
content-type: application/json

{
    "name": "Pizzas"
}

### DELETE ONE CATEGORY
DELETE {{apiUrl}}/category/{{idCategory}}