GET http://localhost:3000/health-check

###
GET http://localhost:3000/product

###
GET http://localhost:3000/product/ca379e84-4bc8-447a-b22b-0fd94a132264

###
POST http://localhost:3000/product
content-type: application/json

{
    "name": "Lily McBride",
    "price": "3212.25",
    "description": "jpW1ZrfZBXld0mkd3h8gaaOQL3dyuW1uAqHiXP1VnBN87UzVmY",
    "categoryId": "5bc954b1-6df9-4126-9224-56a82e897d43"
}

###
PUT http://localhost:3000/category/b6b82772-6d6c-4fe4-9d97-b51fe9b6e694
content-type: application/json

{
    "name": "Categoria alterada"
}

###
DELETE http://localhost:3000/category/b6b82772-6d6c-4fe4-9d97-b51fe9b6e694