### VARIABLES
@apiUrl = http://localhost:3000
@idMenu = 65022c6886f51d3aebf3d4e4


### GET LIST OF MENU
GET {{apiUrl}}/menu

### GET ONE MENU
GET {{apiUrl}}/menu/{{idMenu}}

### POST ONE MENU
POST {{apiUrl}}/menu
content-type: application/json

{
    "period": "NIGHT",
    "products": [
        "650201a12f9694f46ee25855",
        "650201b02f9694f46ee25856",
        "65020a3d4d35188f5d8c5e5a"
    ]
}

### UPDATE ONE CATEGORY
PUT {{apiUrl}}/category/{{idMenu}}
content-type: application/json

{
    "name": "Drinks"
}

### DELETE ONE CATEGORY
DELETE {{apiUrl}}/category/{{idMenu}}