### VARIABLES
@apiUrl = http://localhost:3000
@idCategory = bfa3731d-50af-4aea-90fc-09f2de2cc9bd


### HEALTH CHECK
GET {{apiUrl}}/health-check

### GET LIST OF CATEGORY
GET {{apiUrl}}/category

### GET ONE CATEGORY
GET {{apiUrl}}/category/{{idCategory}}

### POST ONE CATEGORY
POST {{apiUrl}}/category
content-type: application/json

{
    "name": "Tacos"
}

### UPDATE ONE CATEGORY
PUT {{apiUrl}}/category/{{idCategory}}
content-type: application/json

{
    "name": "Categoria alterada"
}

### DELETE ONE CATEGORY
DELETE {{apiUrl}}/category/{{idCategory}}