### VARIABLES
@apiUrl = http://localhost:3000
@idCategory = "6501f5c219cbfa9b999cc7a6"
@idProductUrl = 6501f5cb19cbfa9b999cc7a7

###
GET {{apiUrl}}/product

###
GET {{apiUrl}}/product/{{idProductUrl}}

###
POST {{apiUrl}}/product
content-type: application/json

{
    "name": "Big Burrito",
    "price": "9.00",
    "description": "MAeMvLFTuD4xE8iZKL79",
    "categoryId": {{idCategory}}
}

###
PUT {{apiUrl}}/product/{{idProductUrl}}
content-type: application/json

{
    "name": "Standar",
    "price": "7.00",
    "image": null,
    "description": "jpW1ZrfZBXld0mkd3h8gaaOQL3dyuW1uAqHiXP1VnBN87UzVmY",
    "categoryId": {{idCategory}}
}

###
DELETE {{apiUrl}}/product/8937f6ae-1777-49e7-af42-9a545c7b10c1