### VARIABLES
@apiUrl = http://localhost:3000
@idMenu = 650245ed1ed96030d2fc1eae


### GET LIST OF MENU BASEADO NA HORA
GET {{apiUrl}}/menu

### GET ONE MENU
GET {{apiUrl}}/menu/{{idMenu}}

### POST ONE MENU
POST {{apiUrl}}/menu
content-type: application/json

{
    "period": "NIGHT", 
    "products": [
        "650242598b749dabdeaccebc"
    ]
}

### UPDATE ONE MENU
PUT {{apiUrl}}/menu/{{idMenu}}
content-type: application/json

{
    "period": "DAY",
    "products": [
        "650242598b749dabdeaccebc",
        "650242618b749dabdeaccebd"
    ]
}

### DELETE ONE CATEGORY
DELETE {{apiUrl}}/menu/{{idMenu}}