### VARIABLES
@apiUrl = http://localhost:3000
@idCategory = 650209aded4a57ac70978d87


### GET LIST OF MENU
GET {{apiUrl}}/menu

### GET ONE CATEGORY
GET {{apiUrl}}/category/{{idCategory}}

### POST ONE CATEGORY
POST {{apiUrl}}/category
content-type: application/json

{
    "name": "Drinks"
}

### UPDATE ONE CATEGORY
PUT {{apiUrl}}/category/{{idCategory}}
content-type: application/json

{
    "name": "Drinks"
}

### DELETE ONE CATEGORY
DELETE {{apiUrl}}/category/{{idCategory}}