### VARIABLES
@apiUrl = http://localhost:3000
@idCategory = "650241fa8b749dabdeaccebb"
@idProductUrl = 650242618b749dabdeaccebd

###
GET {{apiUrl}}/product

###
GET {{apiUrl}}/product/{{idProductUrl}}

###
POST {{apiUrl}}/product
content-type: application/json

{
    "name": "Garrafa de àgua gasosa",
    "price": "9.00",
    "description": "500ml",
    "categoryId": {{idCategory}}
}

###
PUT {{apiUrl}}/product/{{idProductUrl}}
content-type: application/json

{
    "name": "X Tudo",
    "price": "19.00",
    "description": "Pão, Hamburguer, Ovo",
    "categoryId": {{idCategory}}
}

###
DELETE {{apiUrl}}/product/{{idProductUrl}}