### VARIABLES
@apiUrl = http://localhost:3000
@idCategory = 6501f88813f44bfa562947ad


### HEALTH CHECK
GET {{apiUrl}}/health-check

### GET LIST OF CATEGORY
GET {{apiUrl}}/category

### GET ONE CATEGORY
GET {{apiUrl}}/category/{{idCategory}}

### POST ONE CATEGORY
POST {{apiUrl}}/category
content-type: application/json

{
    "name": "Tacos"
}

### UPDATE ONE CATEGORY
PUT {{apiUrl}}/category/{{idCategory}}
content-type: application/json

{
    "name": "Burrito"
}

### DELETE ONE CATEGORY
DELETE {{apiUrl}}/category/{{idCategory}}